engine:
  build: .
  expose:
    - '8080'
  ports:
    - '8080:8080'
  volumes:
    - ./rubygems:/usr/local/rvm/gems
    - ./app:/home/app
    - ./entrypoint.sh:/sbin/entrypoint.sh
  links:
    - db
db:
  image: mongo:3.0.0-rc8
  volumes:
    - ./mongo/db:/data/db
    - ./mongo/configdb:/data/configdb
  expose:
    - '27017'
  ports:
    - '27017:27017'
